### ISSUE TITLE
how to pass variables for docker

### ISSUE THREAD

**Issue by roffinator3000** [LightDestory/TG_MediaDownloader#1]
Hello Alessio!
This bot seems to be quite useful and compact, I'd like to try it.

I can't seem to get it running though, docker doesn't accept additional variables and running interactively shows me an error of missing params but doesn't allow to input them. looking through the scripts it seems to me I need to enter the container ant write a JSON file, is that the intended way?

My thought/request is to allow passing the params through docker while starting the container eg as in this compose.yaml (which then could be added in the readme.md as well)
```
services:
  tg_mediadownloader:
    image: "ghcr.io/lightdestory/tg_mediadownloader:master"
    container_name: mediaDl
    volumes:
      - myHome:/home/media/anime
    environment:
      TG_API_ID: 2900000
      TG_API_HASH: "9000000000000000000aaaaaaaaaaaa5"
      TG_BOT_TOKEN: "7XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXMalrE"
    #  TG_MAX_PARALLEL: 2
    #  TG_DL_TIMEOUT: 900
      TG_DOWNLOAD_PATH: "./anime/download"
      TG_AUTHORIZED_USER_ID: 140000000
volumes:
  myHome:
```

As I understand it, setting variables through arg and env shouldn't be that hard ([explained e.g. by baeldung](https://www.baeldung.com/ops/dockerfile-env-variable)). I could try to add them to the docker file as env variables and pass them into arg. Would you be willing to use those arg variables to set the variables your scripts uses?

thank you in advance
Roffi
